overlay_templates:
  - title: "Single Speaker"
    path: "single-speaker-overlay"
    icon: "images/streamyard/single-speaker.png"
    background-image: ""
    speakers:
      - id: 1
        name:
          text: "Speaker"
          font-and-size: "25px Comfortaa"
          x: "20"
          y: "640"
        twitter:
          text: "@speaker"
          font-and-size: "25px Comfortaa"
          x: "300"
          y: "640"
        overlay:
          x: "0"
          y: "600"


  - title: "Side by Side"
    path: "side-by-side-overlay"
    icon: "images/streamyard/side-by-side.png"
    background-image: ""
    speakers:
      - id: 1
        name:
          text: "First Speaker"
          font-and-size: "25px Comfortaa"
          x: "20"
          y: "640"
        twitter:
          text: "@1st-speaker"
          font-and-size: "25px Comfortaa"
          x: "270"
          y: "640"
        overlay:
          x: "0"
          y: "600"
      - id: 2
        name:
          text: "Second Speaker"
          font-and-size: "25px Comfortaa"
          x: "660"
          y: "640"
        twitter:
          text: "@2nd-speaker"
          font-and-size: "25px Comfortaa"
          x: "890"
          y: "640"
        overlay:
          x: "640"
          y: "600"


  - title: "Two Speakers"
    path: "two-speakers-overlay"
    icon: "images/streamyard/2-speakers.png"
    background-image: ""
    speakers:
      - id: 1
        name:
          text: "First Speaker"
          font-and-size: "25px Comfortaa"
          x: "100"
          y: "540"
        twitter:
          text: "@1st-speaker"
          font-and-size: "25px Comfortaa"
          x: "340"
          y: "540"
        overlay:
          x: "80"
          y: "500"
      - id: 2
        name:
          text: "Second Speaker"
          font-and-size: "25px Comfortaa"
          x: "740"
          y: "540"
        twitter:
          text: "@2nd-speaker"
          font-and-size: "25px Comfortaa"
          x: "970"
          y: "540"
        overlay:
          x: "720"
          y: "500"


  - title: "Speaker With Slides"
    path: "speaker-with-slides-overlay"
    icon: "images/streamyard/speaker-with-slides.png"
    speakers:
      - id: 1
        name:
          text: "Speaker"
          font-and-size: "25px Comfortaa"
          x: "100"
          y: "540"
        twitter:
          text: "@speaker"
          font-and-size: "25px Comfortaa"
          x: "340"
          y: "540"
        overlay:
          x: "80"
          y: "500"


  - title: "Slides"
    path: "slides-overlay"
    icon: "images/streamyard/slides.png"
    speakers:
      - id: 1
        name:
          text: "First Speaker"
          font-and-size: "25px Comfortaa"
          x: "20"
          y: "640"
        twitter:
          text: "@speaker"
          font-and-size: "25px Comfortaa"
          x: "300"
          y: "640"
        overlay:
          x: "0"
          y: "600"
